### ISSUE TITLE
مشکل در نسخه ریلیز

### ISSUE THREAD

**Issue by saeedek** [hermamitr/TapsellSDK_v3_ReactNative#4]
با سلام و ممنون از کتابخونه
من یه مشکلی دارم ، برناممو که به صورت دیباگ اجرا می کنم مشکلی نداره تبلیغات رو می تونم ببینم ولی توی نسخه ریلیز تبلیغات نشون داده نمی شن ، و ارروری که دریافت می کنم اینه که گوشی به اینترنت متصل نیست.
با نسخه 28 اندروید کامپایل کردم و نسخه ریکت نیتیو هم
0.61.5
هست.
ممنون میشم کمک کنید
با تشکر

2020-03-31 14:13:05.291 7631-7631/com.toolbox W/System.err: java.lang.NullPointerException: throw with null exception 2020-03-31 14:13:05.291 7631-7631/com.toolbox W/System.err: at ir.tapsell.sdk.j.c.a.a.b(Unknown Source:3) 2020-03-31 14:13:05.291 7631-7631/com.toolbox W/System.err: at ir.tapsell.sdk.i.c.g(Unknown Source:67) 2020-03-31 14:13:05.291 7631-7631/com.toolbox W/System.err: at ir.tapsell.sdk.aa.a(Unknown Source:82) 2020-03-31 14:13:05.291 7631-7631/com.toolbox W/System.err: at ir.tapsell.sdk.Z.a(Unknown Source:48) 2020-03-31 14:13:05.291 7631-7631/com.toolbox W/System.err: at ir.tapsell.sdk.Z.b(Unknown Source:2) 2020-03-31 14:13:05.291 7631-7631/com.toolbox W/System.err: at ir.tapsell.sdk.e.b.a(Unknown Source:10) 2020-03-31 14:13:05.291 7631-7631/com.toolbox W/System.err: at f.n.run(Unknown Source:37) 2020-03-31 14:13:05.291 7631-7631/com.toolbox W/System.err: at android.os.Handler.handleCallback(Handler.java:883) 2020-03-31 14:13:05.291 7631-7631/com.toolbox W/System.err: at android.os.Handler.dispatchMessage(Handler.java:100) 2020-03-31 14:13:05.291 7631-7631/com.toolbox W/System.err: at android.os.Looper.loop(Looper.java:237) 2020-03-31 14:13:05.291 7631-7631/com.toolbox W/System.err: at android.app.ActivityThread.main(ActivityThread.java:7777) 2020-03-31 14:13:05.291 7631-7631/com.toolbox W/System.err: at java.lang.reflect.Method.invoke(Native Method) 2020-03-31 14:13:05.291 7631-7631/com.toolbox W/System.err: at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493) 2020-03-31 14:13:05.291 7631-7631/com.toolbox W/System.err: at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1047)
این از لاگ کت موقعی که می خواد تبلیغ نشون بده

**Comment by mahdi-malv** [comment]
From now on, tapsell-react-native is not supported. Functionality has been moved to [`tapsell-plus`](https://github.com/tapsellorg/TapsellPlusSDK-ReactNativePlugin)

Closing the issue
